/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "claves_rpc.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_rpc_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, init_rpc, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
set_value_rpc_1(int key, char *value1, double_vector V_value2, int *clnt_res,  CLIENT *clnt)
{
	set_value_rpc_1_argument arg;
	arg.key = key;
	arg.value1 = value1;
	arg.V_value2 = V_value2;
	return (clnt_call (clnt, set_value_rpc, (xdrproc_t) xdr_set_value_rpc_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_value_rpc_1(int key, respuesta *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, get_value_rpc,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_respuesta, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_value_rpc_1(int key, char *value1, double_vector V_value2, int *clnt_res,  CLIENT *clnt)
{
	modify_value_rpc_1_argument arg;
	arg.key = key;
	arg.value1 = value1;
	arg.V_value2 = V_value2;
	return (clnt_call (clnt, modify_value_rpc, (xdrproc_t) xdr_modify_value_rpc_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_key_rpc_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, delete_key_rpc,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_rpc_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, exist_rpc,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}