/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "claves_rpc.h"

bool_t
xdr_double_vector (XDR *xdrs, double_vector *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->double_vector_val, (u_int *) &objp->double_vector_len, 32,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_respuesta (XDR *xdrs, respuesta *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_double_vector (xdrs, &objp->V_value2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->todo_ok))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_set_value_rpc_1_argument (XDR *xdrs, set_value_rpc_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_double_vector (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_modify_value_rpc_1_argument (XDR *xdrs, modify_value_rpc_1_argument *objp)
{
	 if (!xdr_int (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->value1, 256))
		 return FALSE;
	 if (!xdr_double_vector (xdrs, &objp->V_value2))
		 return FALSE;
	return TRUE;
}