/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "operaciones.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
get_operation_1(struct user_operation arg1, void *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, get_operation,
		(xdrproc_t) xdr_user_operation, (caddr_t) &arg1,
		(xdrproc_t) xdr_void, (caddr_t) clnt_res,
		TIMEOUT));
}
