/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _OPERACIONES_H_RPCGEN
#define _OPERACIONES_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct user_operation {
	char *username;
	char *operation;
	char *filename;
	char *date_time;
};
typedef struct user_operation user_operation;

#define OPERACIONES 2
#define OPS_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define get_operation 1
extern  enum clnt_stat get_operation_1(struct user_operation , void *, CLIENT *);
extern  bool_t get_operation_1_svc(struct user_operation , void *, struct svc_req *);
extern int operaciones_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define get_operation 1
extern  enum clnt_stat get_operation_1();
extern  bool_t get_operation_1_svc();
extern int operaciones_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_user_operation (XDR *, user_operation*);

#else /* K&R C */
extern bool_t xdr_user_operation ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_OPERACIONES_H_RPCGEN */
