/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "operaciones.h"

bool_t
get_operation_1_svc(struct user_operation arg1, void *result,  struct svc_req *rqstp)
{
	bool_t retval;
	
	// Si no viene con filename (str vacía), no imprimirlo
	if (strncmp(arg1.filename, "", 1) == 0){
		printf("%s %s %s\n", arg1.username, arg1.operation, arg1.date_time);
	}

	printf("%s %s %s %s\n", arg1.username, arg1.operation, arg1.filename, arg1.date_time);

	return retval;
}

int
operaciones_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
